### ISSUE TITLE
Issue http204 with notifications

### ISSUE THREAD

**Issue by saikek** [saikek/RParser#12]
```bash
2016-12-22 18:00:26 INFO  MainClass:42 - Using non-paranoid mode
2016-12-22 18:00:28 WARN  WebClientWrapper:52 - Not Using proxy
2016-12-22 18:00:28 INFO  FileHandler:57 - Created directory with date 2016-12-22
2016-12-22 18:00:28 INFO  GlobalLinksFetcher:57 - Getting number of flats from: https://www.sreality.cz/api/en/v2/estates/count?category_main_cb=1&category_type_cb=1&locality_country_id=112&locality_region_id=10
2016-12-22 18:00:30 INFO  GlobalLinksFetcher:74 - Count of flats from response is: 4499
2016-12-22 18:00:30 INFO  GlobalLinksFetcher:84 - Total number of flats: 4499, per page: 60
2016-12-22 18:00:30 INFO  GlobalLinksFetcher:85 - Number of pages 75
2016-12-22 18:01:17 INFO  DownloadAgent:34 - Creating file with urls for estate to: /home/saikek/estate/2016-12-22/SingleUrl.txt
2016-12-22 18:01:18 INFO  DownloadAgent:55 - Total number of parsed flats: 4498
2016-12-22 18:01:18 INFO  DownloadAgent:117 - Reading estates from /home/saikek/estate/2016-12-22/SingleUrl.txt
2016-12-22 18:01:18 INFO  DownloadAgent:108 - Cleanup results: Total[4498], Duplicates[0], Wrong[0], Exists[0], Usable[4498]
2016-12-22 18:01:30 INFO  QueueClient:48 - Done filling up the queue with estates
2016-12-22 18:20:50 ERROR MainClass:92 - Exception in application
java.lang.RuntimeException: Failed : HTTP error code : 204
        at com.cyberneticscore.realityparser.spider.LinksClient.executeJsonGet(LinksClient.java:34)
        at com.cyberneticscore.realityparser.spider.QueueClient.downloadEstatesFromQueue(QueueClient.java:79)
        at com.cyberneticscore.realityparser.spider.QueueClient.fetchEachEstate(QueueClient.java:37)
        at com.cyberneticscore.realityparser.spider.MainClass.main(MainClass.java:72)
2016-12-22 18:20:50 INFO  EmailSender:21 - Sending e-mail
2016-12-22 18:20:52 INFO  EmailSender:48 - Email was sent
2016-12-22 18:20:53 INFO  PushMessageClient:48 - Response message: Bad Request

```

**Comment by saikek** [comment]
Fixed with 728ca9f
