### ISSUE TITLE
Investigate why this file is created by root

### ISSUE THREAD

**Issue by saikek** [saikek/RParser#14]
```
2017-01-02 18:01:02 ERROR FileHandler:130 - Error writing to
java.io.FileNotFoundException: /tmp/report.txt (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileWriter.<init>(FileWriter.java:107)
        at com.cyberneticscore.realityparser.util.FileHandler.writeReportFile(FileHandler.java:123)
        at com.cyberneticscore.realityparser.spider.GlobalLinksFetcher.fetchGroupEstateDataForToday(GlobalLinksFetcher.java:53)
        at com.cyberneticscore.realityparser.spider.MainClass.main(MainClass.java:66)
```

**Comment by saikek** [comment]
Not observed anymore.
